# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your http://localhost:8888/notebooks/IronHack/GitHub/data-ft-par-labs/Labs/module_1/17.%20Numpy/your-code/main.ipynb#2.-Print-your-NumPy-version.code here
print(np.__version__)

1.19.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
# Method 1
a1 = np.random.random((2,3,5))
a1

array([[[0.23130979, 0.29915157, 0.4602396 , 0.32182011, 0.26021738],
        [0.52124453, 0.04953733, 0.85545794, 0.52523294, 0.42593619],
        [0.14063967, 0.73888257, 0.87403577, 0.21978195, 0.87709559]],

       [[0.31378112, 0.83349683, 0.25811088, 0.78447785, 0.80940327],
        [0.65842691, 0.83458645, 0.2477963 , 0.24295134, 0.60665479],
        [0.17094252, 0.04320954, 0.41670867, 0.90412612, 0.78799166]]])

In [12]:
# Method 2
a2 = np.random.rand(2,3,5)
a2

array([[[0.25170721, 0.77186739, 0.07829589, 0.49763299, 0.62266145],
        [0.13125163, 0.54881125, 0.56339903, 0.95782162, 0.61618857],
        [0.127108  , 0.30993416, 0.05766875, 0.6464959 , 0.89601041]],

       [[0.61917046, 0.94962937, 0.9011445 , 0.82285446, 0.83997099],
        [0.80058544, 0.39020235, 0.43006104, 0.34629576, 0.68124039],
        [0.53302102, 0.75276321, 0.07407467, 0.88572402, 0.02767938]]])

In [13]:
# Method 3
a3 = np.random.randint(100, size=(2,3,5))
a3

array([[[39, 46, 46, 44, 95],
        [65, 12, 60, 79, 72],
        [22, 35, 91, 31, 51]],

       [[50, 91, 65, 17, 35],
        [44, 28, 16, 62, 80],
        [53, 37,  1,  6, 52]]])

#### 4. Print *a*.


In [14]:
# your code here
a1

array([[[0.23130979, 0.29915157, 0.4602396 , 0.32182011, 0.26021738],
        [0.52124453, 0.04953733, 0.85545794, 0.52523294, 0.42593619],
        [0.14063967, 0.73888257, 0.87403577, 0.21978195, 0.87709559]],

       [[0.31378112, 0.83349683, 0.25811088, 0.78447785, 0.80940327],
        [0.65842691, 0.83458645, 0.2477963 , 0.24295134, 0.60665479],
        [0.17094252, 0.04320954, 0.41670867, 0.90412612, 0.78799166]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
b = np.ones((5,2,3), dtype=int)

#### 6. Print *b*.


In [16]:
# your code here
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
b.size == a1.size

True

In [22]:
# your code here
Z = b.size
z = a3.size

In [23]:
z == Z

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [24]:
# your answer here
a1 + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [26]:
np.add(a3, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

<span class="mark">No, because even though they have the same size, they don't have the same shape. The shape of a is (3,2,3,5) while the shape of b is (3,5,2,3).</span>

In [25]:
print(a1.shape == b.shape)

False


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
# your code here
c = b.transpose(1,2,0)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [28]:
a1

array([[[0.23130979, 0.29915157, 0.4602396 , 0.32182011, 0.26021738],
        [0.52124453, 0.04953733, 0.85545794, 0.52523294, 0.42593619],
        [0.14063967, 0.73888257, 0.87403577, 0.21978195, 0.87709559]],

       [[0.31378112, 0.83349683, 0.25811088, 0.78447785, 0.80940327],
        [0.65842691, 0.83458645, 0.2477963 , 0.24295134, 0.60665479],
        [0.17094252, 0.04320954, 0.41670867, 0.90412612, 0.78799166]]])

In [29]:
c 

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [30]:
# your code/answer here
d = a1 + c

In [31]:
d1 = np.add(a3, c) 

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [36]:
# your code/answer here
print(d)
print(d1)

[[[1.23130979 1.29915157 1.4602396  1.32182011 1.26021738]
  [1.52124453 1.04953733 1.85545794 1.52523294 1.42593619]
  [1.14063967 1.73888257 1.87403577 1.21978195 1.87709559]]

 [[1.31378112 1.83349683 1.25811088 1.78447785 1.80940327]
  [1.65842691 1.83458645 1.2477963  1.24295134 1.60665479]
  [1.17094252 1.04320954 1.41670867 1.90412612 1.78799166]]]
[[[40 47 47 45 96]
  [66 13 61 80 73]
  [23 36 92 32 52]]

 [[51 92 66 18 36]
  [45 29 17 63 81]
  [54 38  2  7 53]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [37]:
# your code here
e = np.multiply(a1, c)

In [38]:
e

array([[[0.23130979, 0.29915157, 0.4602396 , 0.32182011, 0.26021738],
        [0.52124453, 0.04953733, 0.85545794, 0.52523294, 0.42593619],
        [0.14063967, 0.73888257, 0.87403577, 0.21978195, 0.87709559]],

       [[0.31378112, 0.83349683, 0.25811088, 0.78447785, 0.80940327],
        [0.65842691, 0.83458645, 0.2477963 , 0.24295134, 0.60665479],
        [0.17094252, 0.04320954, 0.41670867, 0.90412612, 0.78799166]]])

In [39]:
a1

array([[[0.23130979, 0.29915157, 0.4602396 , 0.32182011, 0.26021738],
        [0.52124453, 0.04953733, 0.85545794, 0.52523294, 0.42593619],
        [0.14063967, 0.73888257, 0.87403577, 0.21978195, 0.87709559]],

       [[0.31378112, 0.83349683, 0.25811088, 0.78447785, 0.80940327],
        [0.65842691, 0.83458645, 0.2477963 , 0.24295134, 0.60665479],
        [0.17094252, 0.04320954, 0.41670867, 0.90412612, 0.78799166]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [40]:
# your code/answer here
e == a1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [54]:
# your code here
d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d)

In [64]:
d

array([[[1.47973087, 1.51168978, 1.4774504 , 1.59469624, 1.41571828],
        [1.4906526 , 1.99290375, 1.21129731, 1.84159284, 1.92950742],
        [1.49449081, 1.59778728, 1.90627683, 1.68433697, 1.41703989]],

       [[1.78239943, 1.22459901, 1.14954964, 1.62494431, 1.81308348],
        [1.95101861, 1.32098264, 1.00268051, 1.7993217 , 1.11998565],
        [1.25669031, 1.41118092, 1.07025042, 1.72178409, 1.22002622]]])

In [65]:
d_mean

1.5171222741230277

In [66]:
d_max

1.9929037455403154

In [67]:
d_min

1.0026805124501068

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [41]:
# your code here
f = np.empty((2,3,5))
f

array([[[0.23130979, 0.29915157, 0.4602396 , 0.32182011, 0.26021738],
        [0.52124453, 0.04953733, 0.85545794, 0.52523294, 0.42593619],
        [0.14063967, 0.73888257, 0.87403577, 0.21978195, 0.87709559]],

       [[0.31378112, 0.83349683, 0.25811088, 0.78447785, 0.80940327],
        [0.65842691, 0.83458645, 0.2477963 , 0.24295134, 0.60665479],
        [0.17094252, 0.04320954, 0.41670867, 0.90412612, 0.78799166]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [75]:
f = np.where(d == d_min, 0, d)
f = np.where(d > d_min, 25, f)
f = np.where(d == d_mean, 50, f)
f = np.where(d < d_max, 75, f)
f = np.where(d == d_max, 100, f)
f

array([[[ 75.,  75.,  75.,  75.,  75.],
        [ 75., 100.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.]],

       [[ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.]]])

In [ ]:
f = np.where(d==d_max,100,f)

In [ ]:
# your code here
for i in d, f:
    if d[i] > d_min and i < d_mean:
        f[i]= 25
    elif i > d_mean and i < d_max:
        f[i]= 75


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [76]:
# your code here
f

array([[[ 75.,  75.,  75.,  75.,  75.],
        [ 75., 100.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.]],

       [[ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 75.,  75.,  75.,  75.,  75.]]])

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [77]:
# your code here
g = np.where(f == 100, 'E', f)
g = np.where(f == 75, 'D', g)
g = np.where(f == 50, 'C', g)
g = np.where(f == 25, 'B', g)
g = np.where(f == 0, 'A', g)

g


array([[['D', 'D', 'D', 'D', 'D'],
        ['D', 'E', 'D', 'D', 'D'],
        ['D', 'D', 'D', 'D', 'D']],

       [['D', 'D', 'D', 'D', 'D'],
        ['D', 'D', 'D', 'D', 'D'],
        ['D', 'D', 'D', 'D', 'D']]], dtype='<U32')